# Generated by Django 5.1.1 on 2024-09-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lennonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(null=True, upload_to='lennonapp/files/images'),
        ),
    ]
