# Generated by Django 5.1.1 on 2024-09-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lennonapp', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='lennonapp/files/images'),
        ),
    ]
