# Generated by Django 5.1.1 on 2024-09-05 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lennonapp', '0004_alter_menuitem_image_alter_orderitem_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='menuitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lennonapp.menuitem'),
        ),
    ]
