# Generated by Django 5.1.1 on 2024-09-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lennonapp', '0005_alter_cart_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
