# Generated by Django 5.1.1 on 2024-09-06 14:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lennonapp', '0006_rename_quatity_cart_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('user', 'menuitem')},
        ),
    ]
