# Generated by Django 5.1.1 on 2024-09-06 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lennonapp', '0007_rename_order_orderitem_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='menuitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lennonapp.menuitem'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menuitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lennonapp.menuitem'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menuitem')},
        ),
    ]
