# Generated by Django 5.1.1 on 2024-09-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lennonapp', '0008_alter_menuitem_options_rename_user_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
    ]
